variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" {}
variable "udp_subdomain" {}

terraform {
  backend "s3" {
  }
}
provider "okta" {
  org_name  = "${var.org_name}"
  api_token = "${var.api_token}"
  base_url  = "${var.base_url}"
  version   = "~> 3.0"
}
provider "template" {
  version = "~> 2.1"
}
provider "local" {
  version = "~> 1.2"
}
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_group" "obake_mfa" {
  name        = "Obake MFA"
  description = "(Generated by UDP)"
}
resource "okta_user_schema" "addProfilePictureUriAttribute" {
  index  = "profilePictureUrl"
  title  = "Profile Picture URL"
  type   = "string"
  master = "PROFILE_MASTER"
}
resource "okta_user_schema" "addConsentAttribute" {
  index  = "consent"
  title  = "Consent"
  type   = "string"
  master = "PROFILE_MASTER"
}
resource "okta_app_oauth" "obakeDemoApp" {
  label          = "Obake Demo (Generated by UDP)"
  type           = "browser"
  grant_types    = ["implicit"]
  redirect_uris  = ["https://${var.udp_subdomain}.obake.gambcorp.com"]
  response_types = ["token", "id_token"]
  issuer_mode    = "ORG_URL"
  groups         = ["${data.okta_group.all.id}"]
  consent_method = "TRUSTED"
}
resource "okta_auth_server" "obakeDemo" {
  audiences   = ["*"]
  description = "obake"
  name        = "obake.demo"
}
resource "okta_auth_server_policy" "obakeDefaultPolicy" {
  status           = "ACTIVE"
  name             = "Default"
  description      = "Default"
  priority         = 1
  client_whitelist = ["ALL_CLIENTS"]
  auth_server_id   = "${okta_auth_server.obakeDemo.id}"
}
resource "okta_auth_server_claim" "obakeConsentClaim" {
  name           = "consent"
  status         = "ACTIVE"
  claim_type     = "RESOURCE"
  value_type     = "EXPRESSION"
  value          = "user.consent"
  auth_server_id = "${okta_auth_server.obakeDemo.id}"
}
resource "okta_auth_server_policy_rule" "obakeDefaultRule" {
  auth_server_id       = "${okta_auth_server.obakeDemo.id}"
  policy_id            = "${okta_auth_server_policy.obakeDefaultPolicy.id}"
  status               = "ACTIVE"
  name                 = "Default"
  priority             = 1
  group_whitelist      = ["${okta_group.all.id}"]
  grant_type_whitelist = ["implicit"]
  scope_whitelist      = ["openid", "profile", "email"]
}
resource "okta_trusted_origin" "obakeDemo" {
  name   = "${var.udp_subdomain}.obake.gambcorp.com"
  origin = "https://${var.udp_subdomain}.obake.gambcorp.com"
  scopes = ["CORS", "REDIRECT"]
}
data "template_file" "obakeConfiguration" {
  template = "${file("${path.module}/obake.dotenv.template")}"
  vars = {
    client_id         = "${okta_app_oauth.obakeDemoApp.client_id}"
    auth_server_id    = "${okta_auth_server.obakeDemo.id}"
    domain            = "${var.org_name}.${var.base_url}"
    mfa_group_id = "${okta_group.obake_mfa.id}"
  }
}
resource "local_file" "obakeDotenv" {
  content  = "${data.template_file.obakeConfiguration.rendered}"
  filename = "${path.module}/obake.env"
}
